FROM ghcr.io/astral-sh/uv:python3.13-bookworm

ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssh-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/tests

COPY tests/src/pyproject.toml ./
RUN uv sync --no-cache

COPY tests/src/ ./

ENTRYPOINT ["uv", "run", "pytest"]

CMD ["--junitxml=/tmp/test-results/junit.xml"]
